version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - nestjs_network

volumes:
  postgres_data:

networks:
  nestjs_network:
    driver: bridge 